<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="f974a6dd71ba" failures="1" tests="3" name="user-mike" time="50.36" errors="0" timestamp="2024-08-29T16:10:01 GMT">
  <testcase classname="com.umesh.tests.vendorportal.VendorPortalTest" name="loginTest" time="11.051"/>
  <testcase classname="com.umesh.tests.vendorportal.VendorPortalTest" name="dashboardTest" time="6.062">
    <failure type="java.lang.AssertionError" message="expected [8] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [10]
at com.umesh.tests.vendorportal.VendorPortalTest.dashboardTest(VendorPortalTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- dashboardTest -->
  <testcase classname="com.umesh.tests.vendorportal.VendorPortalTest" name="logoutTest" time="0.0">
    <skipped/>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- user-mike -->
